### ISSUE TITLE
Will reinstalling Rolling edition get rid of bug

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#401]
Can someone test if Cinnamon crashes in a fresh install on real hardware by setting the panel to autohide and then in nemo quickly change directories from the sidebar? At the very least try it on your current install, so that I at least know if reinstalling is going to make a difference.
Since nobody is replying to this in the forum I am putting it up here.

It happens in the Live USB and my oldest snapshots. It does not happen in Software Rendering Mode. Upgrading the system did not fix it. Removing ~/.config/dconf to use the defaults does not fix it. I have no external applets, desklets or extensions installed.
This is the **ERROR**
>(cinnamon:1039): Clutter-CRITICAL **: 22:58:47.674: clutter_actor_iter_next: assertion 'ri->age == ri->root->priv->age' failed
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/lib64/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/bin/cinnamon-launcher", line 78, in wait_for_process
os.execvp(FALLBACK_COMMAND, (FALLBACK_COMMAND,) + FALLBACK_ARGS)
File "/usr/lib64/python3.8/os.py", line 568, in execvp
_execvpe(file, args)
File "/usr/lib64/python3.8/os.py", line 610, in _execvpe
raise last_exc
File "/usr/lib64/python3.8/os.py", line 601, in _execvpe
exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
None: no process found

**Comment by cduke1** [comment]
?
